src/apis/detail/deldetailrating.js, src/apis/detail/getVodData.js, src/apis/detail/getdetailrating.js, src/apis/detail/getmywish_post.js, src/apis/detail/postdetailrating.js, src/apis/detail/postdetailwish.js, src/apis/detail/putdetailrating.js, src/apis/genres/getGenre.js, src/apis/genres/getGenres.js, src/apis/login/getlogin_post.js, src/apis/main/getmain_post.js, src/apis/main/getmood.js, src/apis/mypage/getmypagerating_post.js, src/apis/mypage/getmypagereplay_post.js, src/apis/mypage/getmypagewish_post.js, src/pages/Detail.js
=> :bug: GET rating 에러 수정

src/apis/detail/deldetailrating.js, src/apis/detail/getVodData.js, src/apis/detail/getdetailrating.js, src/apis/detail/getmywish_post.js, src/apis/detail/postdetailrating.js, src/apis/detail/postdetailwish.js, src/apis/detail/putdetailrating.js, src/apis/genres/getGenre.js, src/apis/genres/getGenres.js, src/apis/login/getlogin_post.js, src/apis/main/getmain_post.js, src/apis/main/getmood.js, src/apis/mypage/getmypagerating_post.js, src/apis/mypage/getmypagereplay_post.js, src/apis/mypage/getmypagewish_post.js
=> :alien: HTTPS 적용

src/apis/detail/deldetailrating.js
detailrating 
순서 맨 처음인 api 파일에 주석으로 달아놨습니다..
=> 💩 api 요청에 http, https 엔드포인트 주석처리

package.json, src/apis/detail/deldetailrating.js, src/apis/detail/getVodData.js, src/apis/detail/getdetailrating.js, src/apis/detail/getmywish_post.js, src/apis/detail/postdetailrating.js, src/apis/detail/postdetailwish.js, src/apis/detail/putdetailrating.js, src/apis/genres/getGenre.js, src/apis/genres/getGenres.js, src/apis/login/getlogin_post.js, src/apis/main/__getreload1_post.js, src/apis/main/getmain_post.js, src/apis/main/getmood.js, src/apis/mypage/getmypagerating_post.js, src/apis/mypage/getmypagereplay_post.js, src/apis/mypage/getmypagewish_post.js
- CORS 설정으로 해결
- http에서 https로 리다이렉션을 보내기 때문에 cloudfront 주소도 CORS 설정에 추가 필요함
=> :bug: HTTPS 에러 해결

src/apis/main/__getreload1_post.js, src/apis/main/__getreload2_post.js, src/apis/main/__getreload3_post.js, src/pages/Main.js
- mood, gpts_*를 tags 리스트로 통합 요청
=> :hammer: 3개 템플릿 tags 요소로 통합

src/App.js, src/apis/detail/deldetailrating.js, src/apis/login/getlogin_post.js, src/css/NoResponse.css, src/errors/NoResponse.js, src/pages/Login.js
서버와 연결 에러로 응답 오지 않을 때 보여 줄 페이지 생성
=> :goal_net: 서버 연결 에러 페이지 생성

src/components/DropDownEtc.js, src/css/Navbar.css, src/pages/Mypage.js, src/pages/Navbar.js
=> :goal_net: 마이페이지 에러처리

src/css/NoResponse.css, src/errors/NoResponse.js, src/pages/KidsGenre.js, src/pages/MovieGenre.js, src/pages/Mypage.js, src/pages/TvGenre.js, src/reducer/ReplayReducer.js
장르페이지 api 잘못 쓴 내용 수정
응답없음 페이지 뒤로가기 버튼 생성
=> :zap: 장르 페이지 및 응답없음 페이지 수정

src/css/Genre.css, src/css/Search.css, src/pages/KidsGenre.js, src/pages/MovieGenre.js, src/pages/Mypage.js, src/pages/Search.js, src/pages/TvGenre.js
- response 있는 에러는 문구로 에러 처리
- response 없는 경우는 NoRespose 페이지 이동
- 로딩중인 경우 따로 catch
- null인 경우는 데이터 없음 처리
=> :goal_net: 검색 및 카테고리 에러 처리 완료

src/css/Genre.css, src/css/Login.css, src/css/Mypage.css, src/css/Navbar.css, src/css/Search.css, src/css/StyledComponents.js, src/pages/KidsGenre.js, src/pages/MovieGenre.js, src/pages/Mypage.js, src/pages/TvGenre.js
- 카테고리, 검색, 마이페이지 정렬 수정
- 로그인 페이지 css 개선
=> :lipstick: 정렬을 위한 전체적인 css 수정

src/css/Genre.css, src/css/Navbar.css, src/css/Search.css, src/pages/KidsGenre.js, src/pages/MovieGenre.js, src/pages/Navbar.js, src/pages/TvGenre.js
=> 💄 네브바 관련 및 마이페이지 css 수정

src/css/StyledComponents.js, src/pages/Mypage.js
=> :lipstick: 마이페이지 캐러셀 정렬 맞춤, 이모티콘 추가

src/css/Detail.css, src/css/Mypage.css, src/css/StyledComponents.js, src/pages/Detail.js, src/pages/Mypage.js
💄 마이페이지 정렬 css 수정
⚡ 디테일 연관 컨텐츠 추가 및 정렬
=> ⚡ 디테일 연관 컨텐츠 추가 및 정렬, 마이페이지 정렬

src/css/Detail.css, src/css/Genre.css, src/css/Search.css, src/css/StyledComponents.js, src/pages/Detail.js
⚡ 디테일 페이지 캐러셀 개수 추가 및 정렬
💄 검색/카테고리 페이지 정렬
=> 디테일 캐러셀 개수 추가, 검색/카테고리 페이지 정렬

src/css/Genre.css, src/css/Search.css, src/css/StyledComponents.js
=> :lipstick: 카테고리, 검색 정렬

src/css/Mypage.css, src/css/StyledComponents.js, src/pages/Main.js, src/pages/Mypage.js
- 마이페이지 찜 에러 수정
- 메인페이지 장르 제목 추가
- 마이페이지 정렬 맞춤
=> 🐛 마이페이지, 메인페이지 수정

src/components/DropDownSubsr.js, src/css/Detail.css, src/css/DropDownSubsr.css, src/css/Main.css, src/css/Navbar.css, src/css/StyledComponents.js, src/pages/Detail.js, src/pages/Login.js, src/pages/Navbar.js
💄 네브바 css 수정(홈 버튼 제거)
💄 메인페이지 캐러셀 수정
💄 디테일 페이지 캐러셀 사진 축소 정렬
🎨 로그아웃 시 별점 추가
=> 메인페이지/디테일페이지 캐러셀 수정, 네브바 css 수정, 로그아웃 별점 추가

src/css/Detail.css, src/css/Genre.css, src/pages/Detail.js, src/pages/KidsGenre.js, src/pages/MovieGenre.js, src/pages/Navbar.js, src/pages/TvGenre.js
💄 디테일 타이틀 위치 수정
💄 카테고리 조회 페이지 className 변경 및 padding-bottom 추가
🚧 검색 에러 수정
- 검색 에러는 맥북으로 테스트 필요
=> 💄🚧 디테일 타이틀 위치 수정, 카테고리 조회 페이지 css 수정, 검색 에러 수정

public/index.html, src/components/LoginImgs.js, src/css/Detail.css, src/css/StyledComponents.js, src/pages/Detail.js, src/pages/KidsGenre.js, src/pages/Login.js, src/pages/Main.js, src/pages/MovieGenre.js, src/pages/Mypage.js, src/pages/Search.js, src/pages/TvGenre.js
🥅 이미지 403 에러 제거
🥅 디테일 페이지 <text> 태그 에러 해결
🥅 메인, 검색, 카테고리 페이지 <text> -> <p>로 수정
🥅 StyledComponents 내 text태그 p태그로 변경
🥅 Mixed content 워닝 해결
📝 로그인 이미지 셋 생성 및 메인 추천 타이틀 변경
=> 🥅📝 콘솔 에러 해결 및 로그인 이미지 셋 생성

src/css/Login.css
LoginImg안의 포스터들 넣어서 animation 이용 화면 변경
=> :lipstick: 로그인 화면 포스터 변경

src/css/Login.css
=> :lipstick: 로그인 화면 그라데이션 조정

src/css/DropDownKids.css, src/css/DropDownMovie.css, src/css/DropDownTv.css
=> 💄 카테고리 드롭다운 정렬 및 오타 수정
